### ISSUE TITLE
Zero values not displayed

### ISSUE THREAD

**Issue by bakman2** [zinclabs/zinc#715]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**
Showing values in the search interface

**What action did you take?**
Default search

**What action/response/output did you expect?**
Field to show `0` 

**What actually happened?**
Field is empty

**How to reproduce the issue?**
Inject an object with 0's.

**What version of ZincSearch are you using?**
0.3.6

**Any attachments/screenshots?**
<img width="476" alt="image" src="https://user-images.githubusercontent.com/333960/214133018-6effa05c-f3ea-4595-a061-3047b7b2e8ea.png">

**Which service(s) is this relate to?**
GUI

**Comment by hengfeiyang** [comment]
fixed

**Comment by bakman2** [comment]
@hengfeiyang I am running zinc in docker, pulled latest (image: 'public.ecr.aws/zinclabs/zinc:latest'), issue remains, is this correct ?
